//
//  APIClient.swift
//  MyApp
//
//  Auto-generated by iOS Code Converter
//

import Foundation

actor APIClient {
    static let shared = APIClient()

    let baseURL: String

    private let session = URLSession.shared
    private let decoder: JSONDecoder = {
        let d = JSONDecoder()
        d.keyDecodingStrategy = .convertFromSnakeCase
        d.dateDecodingStrategy = .iso8601
        return d
    }()
    private let encoder: JSONEncoder = {
        let e = JSONEncoder()
        e.keyEncodingStrategy = .convertToSnakeCase
        return e
    }()

    private var authToken: String?

    private init() {
        // TODO: Load from xcconfig / Info.plist
        self.baseURL = Bundle.main.infoDictionary?["API_BASE_URL"] as? String
            ?? "https://api.example.com"
    }

    func setAuthToken(_ token: String?) {
        authToken = token
    }

    // MARK: - HTTP Methods

    func get<T: Decodable>(_ urlString: String) async throws -> T {
        let data = try await performRequest(urlString, method: "GET")
        return try decoder.decode(T.self, from: data)
    }

    func post<T: Decodable>(_ urlString: String, body: any Encodable) async throws -> T {
        let data = try await performRequest(urlString, method: "POST", body: body)
        return try decoder.decode(T.self, from: data)
    }

    func put<T: Decodable>(_ urlString: String, body: any Encodable) async throws -> T {
        let data = try await performRequest(urlString, method: "PUT", body: body)
        return try decoder.decode(T.self, from: data)
    }

    func delete(_ urlString: String) async throws {
        _ = try await performRequest(urlString, method: "DELETE")
    }

    // MARK: - Internal

    private func performRequest(
        _ urlString: String,
        method: String,
        body: (any Encodable)? = nil
    ) async throws -> Data {
        guard let url = URL(string: urlString) else {
            throw APIError.invalidURL(urlString)
        }

        var request = URLRequest(url: url)
        request.httpMethod = method
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")

        if let token = authToken {
            request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        }

        if let body {
            request.httpBody = try encoder.encode(body)
        }

        let (data, response) = try await session.data(for: request)

        guard let httpResponse = response as? HTTPURLResponse else {
            throw APIError.invalidResponse
        }

        guard (200...299).contains(httpResponse.statusCode) else {
            throw APIError.httpError(
                status: httpResponse.statusCode,
                body: String(data: data, encoding: .utf8)
            )
        }

        return data
    }
}

// MARK: - Error Types

enum APIError: Error, LocalizedError {
    case invalidURL(String)
    case invalidResponse
    case httpError(status: Int, body: String?)

    var errorDescription: String? {
        switch self {
        case .invalidURL(let url):
            return "Invalid URL: \(url)"
        case .invalidResponse:
            return "Invalid response from server"
        case .httpError(let status, let body):
            return "HTTP \(status): \(body ?? "No details")"
        }
    }
}

struct EmptyBody: Encodable {}
