//
//  ArticleService.swift
//  MyApp
//
//  Auto-generated by iOS Code Converter
//  Review all TODO comments before using in production
//

import Foundation

// MARK: - Service

struct ArticleService {

    static func getAll(sortBy: ArticleSortBy = "recent", page: Any = 1) async throws -> [Article] {
        let url = "\(APIClient.shared.baseURL)\(baseURL)/articles"
        return try await APIClient.shared.get(url)
    }

    static func getById(id: String) async throws -> Article {
        let url = "\(APIClient.shared.baseURL)\(baseURL)/articles/\(id)"
        return try await APIClient.shared.get(url)
    }

    static func create(input: CreateArticleInput) async throws -> Article {
        let url = "\(APIClient.shared.baseURL)\(baseURL)/articles"
        return try await APIClient.shared.post(url, body: input)
    }

    static func update(id: String, input: CreateArticleInput) async throws -> Article {
        let url = "\(APIClient.shared.baseURL)\(baseURL)/articles/\(id)"
        return try await APIClient.shared.put(url, body: input)
    }

    static func delete(id: String) async throws {
        let url = "\(APIClient.shared.baseURL)\(baseURL)/articles/\(id)"
        try await APIClient.shared.delete(url)
    }

    static func search(query: String) async throws -> [Article] {
        let url = "\(APIClient.shared.baseURL)\(baseURL)/articles/search"
        return try await APIClient.shared.get(url)
    }

}
