//
//  ArticleService.swift
//  MyApp
//
//  Auto-generated by iOS Code Converter
//  Review all TODO comments before using in production
//

// ============================================================
// LEARN: Why Apple does it this way
// ============================================================
//
// 💡 Why Actor for the API Client
//    Actors prevent data races in concurrent code — thread safety guaranteed by the compiler.
//    Web analogy: Like a Web Worker with built-in message passing, but the compiler enforces the safety.
//
// 💡 Why URLSession Instead of fetch()/Axios
//    URLSession is Apple's built-in networking layer — no packages needed.
//    Web analogy: The native fetch() API, but with built-in caching, background downloads, and OS integration.
//
// 💡 Why Swift async/await Looks Like JavaScript's
//    Swift adopted async/await after JavaScript — nearly identical syntax, stricter safety.
//    Web analogy: Same syntax as JS async/await, but with compile-time thread safety checks.
//
// 💡 Why Codable Instead of Manual JSON Parsing
//    Codable lets the compiler generate JSON encoding/decoding automatically.
//    Web analogy: Like Zod validation built into the language, but zero runtime cost.
//
// See learning-notes.md for full explanations.
// ============================================================

import Foundation

// MARK: - Service

struct ArticleService {

    static func getAll(sortBy: ArticleSortBy = "recent", page: Any = 1) async throws -> [Article] {
        let url = "\(APIClient.shared.baseURL)\(baseURL)/articles"
        return try await APIClient.shared.get(url)
    }

    static func getById(id: String) async throws -> Article {
        let url = "\(APIClient.shared.baseURL)\(baseURL)/articles/\(id)"
        return try await APIClient.shared.get(url)
    }

    static func create(input: CreateArticleInput) async throws -> Article {
        let url = "\(APIClient.shared.baseURL)\(baseURL)/articles"
        return try await APIClient.shared.post(url, body: input)
    }

    static func update(id: String, input: CreateArticleInput) async throws -> Article {
        let url = "\(APIClient.shared.baseURL)\(baseURL)/articles/\(id)"
        return try await APIClient.shared.put(url, body: input)
    }

    static func delete(id: String) async throws {
        let url = "\(APIClient.shared.baseURL)\(baseURL)/articles/\(id)"
        try await APIClient.shared.delete(url)
    }

    static func search(query: String) async throws -> [Article] {
        let url = "\(APIClient.shared.baseURL)\(baseURL)/articles/search"
        return try await APIClient.shared.get(url)
    }

}
