//
//  AppConfig.swift
//  SampleApp
//
//  Auto-generated by iOS Code Converter
//  Review all TODO comments before using in production
//

import Foundation

// 💡 Learn: This enum provides type-safe access to build configuration.
//    Values come from xcconfig → Info.plist → Bundle at compile time.
//    Unlike .env, these can't be changed without rebuilding the app.

enum AppConfig {

    static let apiUrl: String = {
        guard let value = Bundle.main.infoDictionary?["API_URL"] as? String else {
            #if DEBUG
            fatalError("Missing config: API_URL — check xcconfig")
            #else
            return ""
            #endif
        }
        return value
    }()
    // Source: NEXT_PUBLIC_API_URL

}
