"""
Learning Notes Generator — produces a companion learning-notes.md
document explaining WHY Apple does things differently from the web.

Each section corresponds to a conversion that happened, with the
educational context organized by topic.
"""

from .annotations import (
    get_annotations_for_file,
    get_all_annotations,
    PATTERN_ANNOTATION_MAP,
)


def generate_learning_notes(manifest: dict, generated_files: list[dict]) -> str:
    """
    Generate a comprehensive learning-notes.md from the conversion results.

    Args:
        manifest: The analysis manifest (from Phase 1)
        generated_files: List of dicts with keys: source_path, output_path, file_type, patterns

    Returns:
        Markdown string with educational content
    """
    lines = []
    lines.append("# Learning Notes — Why Apple Does It This Way")
    lines.append("")
    lines.append("> Auto-generated by iOS Code Converter")
    lines.append("> These notes explain the reasoning behind each conversion decision.")
    lines.append("> Read alongside the generated Swift code to understand not just WHAT")
    lines.append("> changed, but WHY the iOS ecosystem works differently.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Table of contents
    lines.append("## Table of Contents")
    lines.append("")

    # Collect all unique annotations used across the project
    all_used_annotations = []
    seen_titles = set()

    for gf in generated_files:
        file_type = gf.get("file_type", "unknown")
        patterns = gf.get("patterns", [])
        annotations = get_annotations_for_file(file_type, patterns)

        for ann in annotations:
            if ann["title"] not in seen_titles:
                seen_titles.add(ann["title"])
                all_used_annotations.append(ann)

    for i, ann in enumerate(all_used_annotations, 1):
        anchor = ann["title"].lower().replace(" ", "-").replace("(", "").replace(")", "")
        lines.append(f"{i}. [{ann['title']}](#{anchor})")

    lines.append("")
    lines.append("---")
    lines.append("")

    # Per-file summary — what was converted and what to learn
    lines.append("## Conversion Overview")
    lines.append("")
    lines.append("| Source File | Swift File | Key Concepts |")
    lines.append("|---|---|---|")

    for gf in generated_files:
        file_type = gf.get("file_type", "unknown")
        patterns = gf.get("patterns", [])
        annotations = get_annotations_for_file(file_type, patterns)
        concepts = ", ".join(a["title"].split("—")[0].split("Instead")[0].strip()[:30]
                            for a in annotations[:3])
        if len(annotations) > 3:
            concepts += f" +{len(annotations) - 3} more"
        lines.append(
            f"| `{gf.get('source_path', '?')}` "
            f"| `{gf.get('output_path', '?')}` "
            f"| {concepts} |"
        )

    lines.append("")
    lines.append("---")
    lines.append("")

    # Detailed annotations — one section per concept
    lines.append("## Concepts Explained")
    lines.append("")

    for ann in all_used_annotations:
        lines.append(f"### {ann['title']}")
        lines.append("")
        lines.append(f"**TL;DR:** {ann['short']}")
        lines.append("")
        lines.append(ann["detail"])
        lines.append("")

        if ann.get("web_analogy"):
            lines.append(f"**Web Developer Analogy:** {ann['web_analogy']}")
            lines.append("")

        if ann.get("apple_doc"):
            lines.append(f"**Apple Documentation:** {ann['apple_doc']}")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Quick reference cheat sheet
    lines.append("## Quick Reference — Web to iOS Cheat Sheet")
    lines.append("")
    lines.append("| Web Concept | iOS Equivalent | Why Different? |")
    lines.append("|---|---|---|")

    cheat_sheet = [
        ("React Component", "SwiftUI View struct", "Value types are cheaper to create and prevent shared state bugs"),
        ("useState()", "@State var", "Property wrapper — SwiftUI manages storage, you mutate directly"),
        ("useEffect()", ".task { } / .onAppear { }", "Auto-cancels when view disappears — no cleanup needed"),
        ("useContext()", "@Environment", "Type-safe, built-in, with many pre-defined system values"),
        ("Custom Hook", "@Observable class (ViewModel)", "Class with fine-grained property tracking"),
        ("fetch() / Axios", "URLSession", "Built-in, OS-integrated, supports background downloads"),
        ("React Router", "NavigationStack", "Type-safe, value-based instead of string URLs"),
        ("Redux / Zustand", "@Observable + @Environment", "Built into SwiftUI — no packages needed"),
        ("Tailwind classes", "SwiftUI modifiers", "Type-checked function calls instead of string class names"),
        (".env files", "xcconfig files", "Resolved at compile time, not runtime"),
        ("package.json", "Package.swift", "Swift code instead of JSON, built into Xcode"),
        ("localStorage", "UserDefaults / Keychain", "UserDefaults for prefs, Keychain for secrets"),
        ("CSS / className", ".modifier() chain", "Compiler-checked, composable function calls"),
        ("index.tsx + createRoot", "@main App + WindowGroup", "OS manages window lifecycle"),
        ("key prop on lists", "Identifiable protocol", "Compiler-enforced instead of runtime warnings"),
        ("Promise", "async/await + Task", "Same syntax, but with compile-time thread safety"),
    ]

    for web, ios, why in cheat_sheet:
        lines.append(f"| {web} | {ios} | {why} |")

    lines.append("")

    # Philosophy section
    lines.append("## Apple's Design Philosophy — The Bigger Picture")
    lines.append("")
    lines.append("### Safety Over Flexibility")
    lines.append("")
    lines.append(
        "The web ecosystem prioritizes flexibility and developer choice. Apple prioritizes "
        "safety and consistency. Where JavaScript says 'here are building blocks, combine "
        "them however you want,' Swift says 'here's the blessed way to do it, and the "
        "compiler will guide you.' This feels restrictive at first, but it means fewer "
        "categories of bugs, better tooling support, and more consistent codebases."
    )
    lines.append("")
    lines.append("### Value Types by Default")
    lines.append("")
    lines.append(
        "Swift defaults to structs (value types) where JavaScript uses objects (reference "
        "types). This single decision eliminates entire categories of bugs: no accidental "
        "shared state, no 'I mutated this object and now something else broke.' When you "
        "need shared state, you opt in explicitly with classes and actors."
    )
    lines.append("")
    lines.append("### Compile-Time Over Runtime")
    lines.append("")
    lines.append(
        "TypeScript adds compile-time types but they're erased at runtime. Swift types "
        "are real — they affect memory layout, performance, and runtime behavior. Codable "
        "generates real parsing code. NavigationStack enforces real type constraints. This "
        "means more compiler errors, but fewer runtime crashes in production."
    )
    lines.append("")
    lines.append("### Batteries Included")
    lines.append("")
    lines.append(
        "Where a React project might depend on 50+ npm packages, a SwiftUI project often "
        "needs very few external dependencies. Networking (URLSession), state management "
        "(@Observable), navigation (NavigationStack), local storage (UserDefaults), secure "
        "storage (Keychain), animations, accessibility, and thousands of icons (SF Symbols) "
        "are all built into the platform. This reduces dependency management overhead and "
        "ensures consistency across apps."
    )
    lines.append("")

    return "\n".join(lines)


def generate_inline_annotations(file_type: str, patterns: list[dict]) -> list[str]:
    """
    Generate short inline learning comments to embed in a Swift file.
    Returns a list of comment lines to insert near the top of the file.
    """
    annotations = get_annotations_for_file(file_type, patterns)
    if not annotations:
        return []

    lines = []
    lines.append("// ============================================================")
    lines.append("// LEARN: Why Apple does it this way")
    lines.append("// ============================================================")

    for ann in annotations[:4]:  # Limit to 4 inline annotations per file
        lines.append(f"//")
        lines.append(f"// 💡 {ann['title']}")
        lines.append(f"//    {ann['short']}")
        if ann.get("web_analogy"):
            lines.append(f"//    Web analogy: {ann['web_analogy']}")

    lines.append("//")
    lines.append("// See learning-notes.md for full explanations.")
    lines.append("// ============================================================")
    lines.append("")

    return lines
