//
//  ContentView.swift
//  SampleApp
//
//  Auto-generated by iOS Code Converter
//  Review all TODO comments before using in production
//

import SwiftUI

struct ContentView: View {

    var body: some View {
            UserCardView()
    }
}

#Preview {
    ContentView()
}
