//
//  SampleAppApp.swift
//  SampleApp
//
//  Auto-generated by iOS Code Converter
//  Review all TODO comments before using in production
//

import SwiftUI

// 💡 Learn: @main marks the app entry point — like index.tsx with createRoot().render(<App />)
//    WindowGroup creates the root window. The OS manages the window lifecycle.

@main
struct SampleAppApp: App {

    // MARK: - App State

    // 💡 Learn: @State here keeps ViewModels alive for the app's lifetime.
    //    Equivalent to wrapping your React app in Context providers.
    @State private var authViewModel = AuthViewModel()

    var body: some Scene {
        WindowGroup {
            Group {
                if authViewModel.isAuthenticated {
                    ContentView()
                } else {
                    LoginView()
                }
            }
            .environment(authViewModel)
        }
    }
}
