// swift-tools-version: 5.9
// Package.swift — SampleApp
//
// Auto-generated by iOS Code Converter
//
// 💡 Learn: Package.swift is the iOS equivalent of package.json.
//    It's actual Swift code (not JSON), and SPM is built into Xcode.
//    Many web dependencies map to built-in Apple frameworks — no package needed.
//
// The following web dependencies are BUILT INTO iOS (no package needed):
//   - axios
//   - date-fns
//   - react
//   - react-router-dom
//

import PackageDescription

let package = Package(
    name: "SampleApp",
    platforms: [
        .iOS(.v17_0),
    ],
    dependencies: [
        // No external dependencies needed — Apple frameworks cover everything!
    ],
    targets: [
        .executableTarget(
            name: "SampleApp",
            path: "Sources/SampleApp"
        ),
        .testTarget(
            name: "SampleAppTests",
            dependencies: ["SampleApp"],
            path: "Tests/SampleAppTests"
        ),
    ]
)
