"""
BUILD-10: Test stub generation.

Emits XCTest skeleton files so developers have a clear testing entry point
right after conversion. Generates one test file per ViewModel and per service,
plus a single MockURLProtocol helper for network-dependent tests.

Educational note: iOS testing relies on @testable import to access internal
symbols and emphasises async test patterns far more than typical Jest setups,
because actor isolation and Sendable types can't be papered over with mocks.
"""

from pathlib import Path


def _sanitize(name: str) -> str:
    """Strip non-identifier characters and ensure a leading letter."""
    cleaned = "".join(c for c in name if c.isalnum() or c == "_")
    if not cleaned or not cleaned[0].isalpha():
        cleaned = "T" + cleaned
    return cleaned


def generate_viewmodel_test(app_name: str, vm_name: str) -> str:
    """XCTest stub for a single ViewModel."""
    safe = _sanitize(vm_name)
    return f"""//
//  {safe}Tests.swift
//  {app_name}Tests
//
//  Auto-generated by iOS Code Converter — fill in TODOs to cover real behavior.
//

import XCTest
@testable import {app_name}

// 💡 Learn: XCTestCase is the iOS equivalent of a Jest describe block.
//    setUp() runs before each test, tearDown() after. Use `sut` (System Under Test)
//    as the conventional variable name to make tests easy to scan.

@MainActor
final class {safe}Tests: XCTestCase {{

    var sut: {safe}!

    override func setUp() async throws {{
        try await super.setUp()
        sut = {safe}()
    }}

    override func tearDown() async throws {{
        sut = nil
        try await super.tearDown()
    }}

    func testInitialState() {{
        // TODO: Verify the ViewModel's initial published state.
        // Example assertions:
        //   XCTAssertNil(sut.user)
        //   XCTAssertFalse(sut.isLoading)
        //   XCTAssertEqual(sut.items.count, 0)
        XCTAssertNotNil(sut)
    }}

    func testAsyncDataLoading() async throws {{
        // TODO: Drive an async method and assert resulting state.
        // Example:
        //   await sut.fetchData()
        //   XCTAssertNotNil(sut.data)
        //   XCTAssertFalse(sut.isLoading)
    }}

    func testErrorPath() async throws {{
        // TODO: Inject a failing service/MockURLProtocol and assert sut surfaces the error.
        //   await sut.fetchData()
        //   XCTAssertNotNil(sut.error)
    }}
}}
"""


def generate_service_test(app_name: str, service_name: str) -> str:
    """XCTest stub for a service/API client. Uses MockURLProtocol for isolation."""
    safe = _sanitize(service_name)
    return f"""//
//  {safe}Tests.swift
//  {app_name}Tests
//
//  Auto-generated by iOS Code Converter.
//

import XCTest
@testable import {app_name}

// 💡 Learn: Network code is tested by injecting a custom URLProtocol into a
//    URLSessionConfiguration. MockURLProtocol (see Mocks/MockURLProtocol.swift)
//    intercepts requests so tests stay hermetic — no real HTTP traffic.

final class {safe}Tests: XCTestCase {{

    var session: URLSession!

    override func setUp() {{
        super.setUp()
        let config = URLSessionConfiguration.ephemeral
        config.protocolClasses = [MockURLProtocol.self]
        session = URLSession(configuration: config)
    }}

    override func tearDown() {{
        session = nil
        MockURLProtocol.requestHandler = nil
        super.tearDown()
    }}

    func testSuccessfulRequestDecodes() async throws {{
        // TODO: Configure MockURLProtocol.requestHandler to return canned JSON
        //       matching your DTO, then call the service and assert the parsed result.
        MockURLProtocol.requestHandler = {{ request in
            let response = HTTPURLResponse(
                url: request.url!,
                statusCode: 200,
                httpVersion: nil,
                headerFields: nil
            )!
            let data = Data("{{}}".utf8)
            return (response, data)
        }}

        // let result = try await {safe}(session: session).fetchSomething()
        // XCTAssertNotNil(result)
    }}

    func testServerErrorThrows() async {{
        MockURLProtocol.requestHandler = {{ request in
            let response = HTTPURLResponse(
                url: request.url!,
                statusCode: 500,
                httpVersion: nil,
                headerFields: nil
            )!
            return (response, Data())
        }}

        // do {{
        //     _ = try await {safe}(session: session).fetchSomething()
        //     XCTFail("Expected to throw")
        // }} catch {{
        //     XCTAssertTrue(error is APIError)
        // }}
    }}
}}
"""


def generate_mock_url_protocol(app_name: str) -> str:
    """Reusable MockURLProtocol so service tests don't hit the network."""
    return f"""//
//  MockURLProtocol.swift
//  {app_name}Tests
//
//  A URLProtocol subclass that intercepts URLSession requests for tests.
//  Configure MockURLProtocol.requestHandler before each test to return canned
//  responses, then inject the configured session into the system under test.
//

import Foundation

final class MockURLProtocol: URLProtocol {{

    static var requestHandler: ((URLRequest) throws -> (HTTPURLResponse, Data))?

    override class func canInit(with request: URLRequest) -> Bool {{ true }}
    override class func canonicalRequest(for request: URLRequest) -> URLRequest {{ request }}

    override func startLoading() {{
        guard let handler = MockURLProtocol.requestHandler else {{
            client?.urlProtocol(
                self,
                didFailWithError: NSError(
                    domain: "MockURLProtocol",
                    code: -1,
                    userInfo: [NSLocalizedDescriptionKey: "No requestHandler configured"]
                )
            )
            return
        }}

        do {{
            let (response, data) = try handler(request)
            client?.urlProtocol(self, didReceive: response, cacheStoragePolicy: .notAllowed)
            client?.urlProtocol(self, didLoad: data)
            client?.urlProtocolDidFinishLoading(self)
        }} catch {{
            client?.urlProtocol(self, didFailWithError: error)
        }}
    }}

    override func stopLoading() {{
        // no-op — synchronous handler completes during startLoading()
    }}
}}
"""


def generate_smoke_test(app_name: str) -> str:
    """A trivial test that verifies the test target links and runs."""
    return f"""//
//  {app_name}Tests.swift
//  {app_name}Tests
//
//  Auto-generated by iOS Code Converter.
//

import XCTest
@testable import {app_name}

// 💡 Learn: This file exists so `swift test` always has at least one test
//    to run. Per-ViewModel and per-service tests live alongside it.

final class {app_name}SmokeTests: XCTestCase {{

    func testAppLinks() {{
        // If this fails, the test target isn't seeing the app module —
        // check Package.swift's testTarget(dependencies:).
        XCTAssertTrue(true)
    }}
}}
"""


def generate_test_files(
    app_name: str,
    view_models: list[dict],
    services: list[dict],
) -> dict[str, str]:
    """Produce all test files keyed by their path inside the project root."""
    files: dict[str, str] = {}
    test_dir = f"Tests/{app_name}Tests"

    files[f"{test_dir}/{app_name}Tests.swift"] = generate_smoke_test(app_name)
    files[f"{test_dir}/Mocks/MockURLProtocol.swift"] = generate_mock_url_protocol(app_name)

    seen: set[str] = set()
    for vm in view_models:
        name = _sanitize(vm.get("name", ""))
        if not name or name in seen:
            continue
        seen.add(name)
        files[f"{test_dir}/ViewModels/{name}Tests.swift"] = generate_viewmodel_test(app_name, name)

    for svc in services:
        name = _sanitize(svc.get("name", ""))
        if not name or name in seen:
            continue
        seen.add(name)
        files[f"{test_dir}/Services/{name}Tests.swift"] = generate_service_test(app_name, name)

    return files
