//
//  AuthViewModel.swift
//  MyApp
//
//  Auto-generated by iOS Code Converter
//  Review all TODO comments before using in production
//

// ============================================================
// LEARN: Why Apple does it this way
// ============================================================
//
// 💡 Why @Observable Class for ViewModels
//    @Observable makes a class's properties automatically trigger view updates.
//    Web analogy: Like a custom hook with automatic fine-grained reactivity (similar to Solid.js signals).
//
// 💡 Why MVVM Instead of Component + Hook
//    MVVM separates state/logic (ViewModel) from UI (View) — Apple's recommended pattern.
//    Web analogy: Like separating a React component's logic into a custom hook, but as a formalized pattern.
//
// 💡 Why @State Instead of useState()
//    @State tells SwiftUI to own and persist this value across re-renders.
//    Web analogy: Like useState(), but you write directly to the variable instead of calling a setter.
//
// 💡 Why .task {} Instead of useEffect()
//    .task starts async work when a view appears and auto-cancels when it disappears.
//    Web analogy: Like useEffect with automatic cleanup — cancels async work when the component unmounts.
//
// See learning-notes.md for full explanations.
// ============================================================

import Foundation
import SwiftUI

@Observable
class AuthViewModel {

    // MARK: - State

    var user: AuthState["user"]? = nil
    var token: String? = nil
    var isLoading: Bool = true

    // MARK: - Computed Properties

    var isAuthenticated: Bool { user != nil }

    // MARK: - Initialization

    init() {
        Task { await loadInitialData() }
    }

    // MARK: - Methods

    func loadInitialData() async {
        // TODO: Port: getItem()
        // TODO: Port: setToken()
        await fetchUser()
        // TODO: Port: setIsLoading()
    }

    func fetchUser(authToken: String) async throws {
        do {
            // TODO: Call API: ${process.env.NEXT_PUBLIC_API_URL}/auth/me
            // let result: ResponseType = try await APIClient.shared.get(url)
            // TODO: Set user = userData
            token = nil
            isLoading = false
        } catch {
            // TODO: Handle error
            print("Error in \(#function): \(error)")
        }
    }

    func login(email: String, password: String) async throws {
        do {
            // TODO: Call API: ${process.env.NEXT_PUBLIC_API_URL}/auth/login
            // let result: ResponseType = try await APIClient.shared.get(url)
            // TODO: Assign decoded response to user
            // TODO: Assign decoded response to token
        } catch {
            // TODO: Handle error
            print("Error in \(#function): \(error)")
        }
    }

    func logout() {
        user = nil
        token = nil
        UserDefaults.standard.removeObject(forKey: "auth_token")
    }

    func refreshToken() async throws {
        do {
            // TODO: Call API: ${process.env.NEXT_PUBLIC_API_URL}/auth/refresh
            // let result: ResponseType = try await APIClient.shared.get(url)
            // TODO: Assign decoded response to token
        } catch {
            // TODO: Handle error
            print("Error in \(#function): \(error)")
        }
    }

}
