//
//  AuthViewModel.swift
//  MyApp
//
//  Auto-generated by iOS Code Converter
//  Review all TODO comments before using in production
//

import Foundation
import SwiftUI

@Observable
class AuthViewModel {

    // MARK: - State

    var user: AuthState["user"]? = nil
    var token: String? = nil
    var isLoading: Bool = true

    // MARK: - Computed Properties

    var isAuthenticated: Bool { user != nil }

    // MARK: - Initialization

    init() {
        Task { await loadInitialData() }
    }

    // MARK: - Methods

    func loadInitialData() async {
        // TODO: Port: getItem()
        // TODO: Port: setToken()
        await fetchUser()
        // TODO: Port: setIsLoading()
    }

    func fetchUser(authToken: String) async throws {
        do {
            // TODO: Call API: ${process.env.NEXT_PUBLIC_API_URL}/auth/me
            // let result: ResponseType = try await APIClient.shared.get(url)
            // TODO: Set user = userData
            token = nil
            isLoading = false
        } catch {
            // TODO: Handle error
            print("Error in \(#function): \(error)")
        }
    }

    func login(email: String, password: String) async throws {
        do {
            // TODO: Call API: ${process.env.NEXT_PUBLIC_API_URL}/auth/login
            // let result: ResponseType = try await APIClient.shared.get(url)
            // TODO: Assign decoded response to user
            // TODO: Assign decoded response to token
        } catch {
            // TODO: Handle error
            print("Error in \(#function): \(error)")
        }
    }

    func logout() {
        user = nil
        token = nil
        UserDefaults.standard.removeObject(forKey: "auth_token")
    }

    func refreshToken() async throws {
        do {
            // TODO: Call API: ${process.env.NEXT_PUBLIC_API_URL}/auth/refresh
            // let result: ResponseType = try await APIClient.shared.get(url)
            // TODO: Assign decoded response to token
        } catch {
            // TODO: Handle error
            print("Error in \(#function): \(error)")
        }
    }

}
