//
//  UserCardView.swift
//  MyApp
//
//  Auto-generated by iOS Code Converter
//  Review all TODO comments before using in production
//

import SwiftUI

struct User: Codable, Identifiable {
    let id: String
    let name: String
    let email: String
    let avatarUrl: String
    let role: String
    let createdAt: String
}

struct UserCardView: View {
    // MARK: - Props

    let userId: String
    var showActions: Bool = true }: UserCardProps

    // MARK: - State

    @State private var user: User? = nil
    @State private var isLoading: Bool = true
    @State private var isFavorite: Bool = false

    // MARK: - Navigation
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        VStack(alignment: .center, spacing: 16) {
            Image("user.avatarUrl")
                .resizable()
                .scaledToFit()
                .frame(width: 80)
                .frame(width: 80)
                .frame(height: 80)
                .frame(height: 80)
                .clipShape(Circle())
            VStack {
            }
            .multilineTextAlignment(.center)
            Text(user.email)
                .font(.caption)
                .foregroundStyle(.secondary)
            Text(user.role)
                .padding(.horizontal, 8)
                .padding(.vertical, 4)
                .font(.caption2)
                .fontWeight(.medium)
                .background(.blue.opacity(0.15))
                .foregroundStyle(.blue)
                .clipShape(Circle())
            // TODO: Convert <element> element
            EmptyView()
            if showActions {
                // TODO: Convert <element> element
                EmptyView()
            }
        }
        .background(.white)
        .clipShape(RoundedRectangle(cornerRadius: 12))
        .shadow(radius: 4)
        .padding(24)
    }

    // MARK: - Actions

    func handleFavorite() {
        isFavorite = newValue
        // TODO: Persist to UserDefaults
    }
}

#Preview {
    UserCardView(userId: "Sample")
}
